Repository PlaceOS/staff-api, pull requests merged in 2022-05, with the labels that each got.

#188 feat: add support for delegated API access
  Dockerfile
  docker-compose.yml
  shard.lock
  spec/models/tenant_spec.cr
  src/controllers/tenants.cr
  src/controllers/utilities/multi_tenant.cr
  src/migrations/0018_add_delegated_to_tenants.cr
  src/models/tenant.cr
Labels: type: enhancement

#189 feat(bookings): adjust booking limit checks
  spec/controllers/bookings_spec.cr
  src/controllers/bookings.cr
Labels: type: enhancement

#185 refactor: set app name to `staff-api`
  src/constants.cr
Labels: type: refactor

#190 feat(controllers/bookings): add include checked out flag
  src/controllers/bookings.cr
Labels: type: enhancement, Priority: High, product: placeos, focus: backend

#191 chore(bookings): refactor checkin function
  spec/controllers/bookings_spec.cr
  src/controllers/bookings.cr
  src/models/booking.cr
Labels: type: chore

#192 feat: add group related routes
  shard.lock
  spec/controllers/group_spec.cr
  spec/fixtures/groups/index.json
  spec/fixtures/groups/index_filtered.json
  spec/fixtures/groups/show.json
  src/controllers/application.cr
  src/controllers/groups.cr
  src/controllers/staff.cr
  src/error.cr
Labels: type: enhancement, Priority: High, product: placeos, focus: backend
