Repository PlaceOS/staff-api, pull requests merged in 2022-10, with the labels that each got.

#223 feat: add support for running using a service account
  OPENAPI_DOC.yml
  spec/models/tenant_spec.cr
  src/controllers/calendars.cr
  src/controllers/events.cr
  src/controllers/tenants.cr
  src/controllers/utilities/placeos-helpers.cr
  src/migrations/0020_add_service_account_to_tenants.cr
  src/models/tenant.cr
Labels: type: enhancement

#227 fix(events): patching extension metadata
  src/controllers/events.cr
Labels: type: bug

#208 feat(outlook): generate plugin xml manifest
  spec/controllers/outlook_spec.cr
  spec/models/tenant_spec.cr
  src/controllers/outlook.cr
  src/controllers/tenants.cr
  src/migrations/0021_add_outlook_config_to_tenants.cr
  src/models/outlook_manifest.cr
  src/models/tenant.cr
  src/models/tenant/outlook_config.cr
Labels: type: enhancement

#228 chore: update openapi docs and bump deps
  OPENAPI_DOC.yml
  shard.lock
Labels: type: chore

#230 fix(outlook): adjust outlook config
  src/controllers/outlook.cr
  src/models/tenant/outlook_config.cr
Labels: type: bug

#231 fix(models/tenant): allow credentials to be nil
  src/models/tenant.cr
Labels: type: bug

#233 fix(visitor_checkin): when running in delegated permissions mode
  Dockerfile
  docker-compose.yml
  shard.lock
  spec/controllers/events_spec.cr
  src/controllers/application.cr
  src/controllers/bookings.cr
  src/controllers/events.cr
  src/controllers/guests.cr
  src/controllers/utilities/multi_tenant.cr
  src/models/event_metadata.cr
Labels: type: bug

#234 fix(bookings): improve consistency between requests and responses
  OPENAPI_DOC.yml
  spec/controllers/bookings_spec.cr
  spec/controllers/calendars_spec.cr
  src/controllers/bookings.cr
  src/controllers/events.cr
  src/controllers/tenants.cr
  src/models/attendee.cr
  src/models/booking.cr
  src/models/guest.cr
  src/models/tenant.cr
Labels: type: bug
