Repository PlaceOS/staff-api, pull requests merged in 2022-06, with the labels that each got.

#193 chore: bump shards
  shard.lock
Labels: type: chore

#194 fix(events): update on graph api where host event switch not made
  src/controllers/events.cr
Labels: type: bug, Priority: High, focus: backend

#195 feat(events): add dedicated metadata update methods
  shard.lock
  spec/controllers/events_spec.cr
  spec/fixtures/events/o365/events_query.json
  src/controllers/events.cr
Labels: type: enhancement, product: placeos, focus: backend, squad: core

#196 feat(bookings): checked_in to canclled state transition
  spec/controllers/bookings_spec.cr
  src/models/booking.cr
Labels: type: enhancement

#197 chore: migrate to action-controller 5
  shard.lock
  shard.yml
  spec/controllers/authorization_spec.cr
  spec/controllers/bookings_spec.cr
  spec/controllers/calendars_spec.cr
  spec/controllers/events_spec.cr
  spec/controllers/group_spec.cr
  spec/controllers/guests_spec.cr
  spec/controllers/staff_spec.cr
  spec/controllers/tenants_spec.cr
  spec/models/tenant_spec.cr
  spec/spec_helper.cr
  src/controllers/application.cr
  src/controllers/calendars.cr
  src/controllers/events.cr
Labels: type: chore

#198 fix: use correct routes for calendar view with delegated access
  shard.lock
  src/controllers/events.cr
  src/models/tenant.cr
Labels: type: bug

#200 fix(calendar): downcase candidate keys
  src/controllers/calendars.cr
Labels: type: bug
