Repository PlaceOS/staff-api, pull requests merged in 2022-02, with the labels that each got.

#146 feat(bookings): add current_state and history
  shard.lock
  shard.yml
  spec/controllers/bookings_spec.cr
  spec/spec_helper.cr
  src/controllers/bookings.cr
  src/migrations/0014_add_history_to_bookings.cr
  src/models/booking.cr
  src/models/booking/history.cr
Labels: type: enhancement

#149 feat(bookings): add department field
  shard.lock
  shard.yml
  spec/controllers/bookings_spec.cr
  src/controllers/bookings.cr
  src/migrations/0015_add_department_to_bookings.cr
  src/models/booking.cr
  src/models/tenant.cr
Labels: product: placeos, priority: medium, focus: backend

#150 refactor: central build CI
  .github/workflows/build-dev-image.yml
  .github/workflows/build.yml
  README.md
Labels: focus: devops, type: refactor

#156 fix: incomplete centralised ci
  .github/workflows/ci.yml
  Dockerfile.test
  docker-compose.yml
Labels: type: bug, type: refactor

#151 refactor(tenant): improve uniqueness constraint
  spec/controllers/guests_spec.cr
  spec/models/tenant_spec.cr
  src/constants.cr
  src/controllers/application.cr
  src/migrations/0016_add_unique_constraint.cr
  src/models/guest.cr
  src/models/tenant.cr
Labels: type: enhancement, type: security
