Repository PlaceOS/staff-api, pull requests merged in 2022-04, with the labels that each got.

#168 fix(controllers/tenants): update to support limits
  src/controllers/tenants.cr
Labels: type: bug, priority: medium, focus: backend, squad: core

#169 fix(bookings): correct logic
  spec/controllers/bookings_spec.cr
  src/controllers/bookings.cr
Labels: type: bug

#170 feat(calendars): precise free/busy availability requests
  shard.lock
  spec/controllers/bookings_spec.cr
  spec/controllers/calendars_spec.cr
  spec/controllers/guests_spec.cr
  src/controllers/bookings.cr
  src/controllers/calendars.cr
Labels: type: enhancement

#175 chore: bump placeos dependencies
  Dockerfile
  shard.lock
  shard.override.yml
  shard.yml
Labels: priority: critical, type: chore

#176 feat(controllers/events): add support for declining events
  shard.lock
  src/controllers/events.cr
Labels: type: enhancement, product: placeos, focus: backend

#179 feat(booking): change error code on booking limits
  spec/controllers/bookings_spec.cr
  src/controllers/application.cr
  src/controllers/bookings.cr
  src/error.cr
Labels: type: enhancement

#180 feat(migrations/migrate_user_ids): add user_id migrations
  src/migrations/0017_migrate_user_id.cr
Labels: type: enhancement
