Repository PlaceOS/staff-api, pull requests merged in 2023-08, with the labels that each got.

#288 fix(events): check not required with delegated access PPT-758
  src/controllers/bookings.cr
  src/controllers/events.cr
Labels: type: bug

#287 refactor(events): [PPT 503] replace #not_nil! with more specific errors
  .ameba.yml
  OPENAPI_DOC.yml
  src/controllers/application.cr
  src/controllers/events.cr
  src/error.cr
Labels: type: refactor

#290 fix(events): failed metadata lookup on recurring booking edit [PPT-723]
  src/controllers/application.cr
  src/controllers/events.cr
Labels: type: bug

#291 chore(shard.lock): update shards
  shard.lock
Labels: type: chore

#292 feat: improve permissions checks
  shard.lock
  spec/controllers/bookings_spec.cr
  spec/controllers/calendars_spec.cr
  spec/controllers/events_spec.cr
  spec/controllers/helpers/event_helper.cr
  spec/spec_helper.cr
  src/controllers/bookings.cr
  src/controllers/events.cr
  src/controllers/utilities/current-user.cr
  src/controllers/utilities/placeos-helpers.cr
Labels: type: enhancement

#293 fix(calendar): availability check
  src/controllers/calendars.cr
Labels: type: bug

#294 feat(events): skip some checks when in delegated mode
  src/controllers/events.cr
Labels: type: enhancement
