Repository PlaceOS/staff-api, pull requests merged in 2023-03, with the labels that each got.

#260 feat(survey): soft-delete questions if they are used in a survey
  OPENAPI_DOC.yml
  spec/controllers/surveys/questions_spec.cr
  src/controllers/surveys/questions.cr
  src/models/survey/question.cr
Labels: type: enhancement

#262 fix(survey): survey questions deleted json property
  spec/controllers/surveys/questions_spec.cr
  src/controllers/surveys/questions.cr
  src/models/survey/question.cr
Labels: type: bug

#261 chore: update shards
  shard.lock
Labels: type: chore

#264 fix(events): regression caused by missing calendar id
  Dockerfile
  OPENAPI_DOC.yml
  src/controllers/events.cr
Labels: type: bug

#265 feat(event_metadata): provide additional options for metadata queries
  OPENAPI_DOC.yml
  shard.lock
  src/controllers/application.cr
  src/controllers/events.cr
  src/models/event_metadata.cr
Labels: type: enhancement

#266 feat(db): support additional connection details
  shard.lock
  src/constants.cr
Labels: type: enhancement

#267 feat(events): patch metadata lookup using ical uid
  OPENAPI_DOC.yml
  shard.lock
  src/controllers/events.cr
Labels: type: enhancement

#268 feat(events): decorate events with system data where possible
  src/controllers/events.cr
Labels: type: enhancement
