Repository PlaceOS/staff-api, pull requests merged in 2023-06, with the labels that each got.

#281 fix(bookings): add default response status to attendees
  src/controllers/bookings.cr
Labels: type: bug

#280 feat(bookings): add support for linking bookings
  OPENAPI_DOC.yml
  shard.lock
  spec/controllers/helpers/booking_helper.cr
  spec/controllers/helpers/survey_helper.cr
  spec/migration/Dockerfile
  spec/migration/db/migrations/20221103144813_add_doorkeeper_table.sql
  spec/migration/db/migrations/20221103144834_add_condo_table.sql
  spec/migration/db/migrations/20221103181928_add_api_key_table.sql
  spec/migration/db/migrations/20221103181946_add_asset_table.sql
  spec/migration/db/migrations/20221103181954_add_repo_table.sql
  spec/migration/db/migrations/20221103182003_add_driver_table.sql
  spec/migration/db/migrations/20221103182008_add_edge_table.sql
  spec/migration/db/migrations/20221103182015_add_mod_table.sql
  spec/migration/db/migrations/20221103182025_add_zone_table.sql
  spec/migration/db/migrations/20221103182030_add_sets_table.sql
  spec/migration/db/migrations/20221103182036_add_sys_table.sql
  spec/migration/db/migrations/20221103182045_add_metadata_table.sql
  spec/migration/db/migrations/20221103182052_add_user_table.sql
  spec/migration/db/migrations/20221103182102_add_ldap_strat_table.sql
  spec/migration/db/migrations/20221103182109_add_oauth_strat_table.sql
  spec/migration/db/migrations/20221103182121_add_adfs_strat_table.sql
  spec/migration/db/migrations/20221103182131_add_authority_table.sql
  spec/migration/db/migrations/20221103182136_add_ass_table.sql
  spec/migration/db/migrations/20221103182144_add_broker_table.sql
  spec/migration/db/migrations/20221103182204_add_json_schema_table.sql
  spec/migration/db/migrations/20221103182211_add_trigger_table.sql
  spec/migration/db/migrations/20221103182218_add_trig_table.sql
  spec/migration/db/migrations/20221103182226_add_authentication_table.sql
  spec/migration/db/migrations/20221103182518_add_stats_table.sql
  spec/migration/db/migrations/20230224115858_add_sys_booking_feat.sql
  spec/migration/db/migrations/20230314100503_alter_user_table.sql
  spec/migration/db/migrations/20230406153149_add_tenant_table.sql
  spec/migration/db/migrations/20230406225814_add_event_metadata_table.sql
  spec/migration/db/migrations/20230416212548_add_guest_table.sql
  spec/migration/db/migrations/20230416213508_add_attendee_table.sql
  spec/migration/db/migrations/20230416215414_add_booking_table.sql
  spec/migration/db/migrations/20230416220259_add_survey_table.sql
  spec/migration/db/migrations/20230517131159_add_linked_booking.sql
  src/controllers/bookings.cr
  src/controllers/events.cr
  src/migrations/0029_alter_attendees_booking_id.cr
  src/migrations/0030_alter_enum_trigger_type.cr
  src/models/event.cr
Labels: type: enhancement

#282 chore: add linked booking to event spec
  shard.lock
  spec/controllers/bookings_spec.cr
  spec/controllers/helpers/booking_helper.cr
  src/controllers/bookings.cr
Labels: type: chore

#283 feat(events): add push event endpoint
  shard.lock
  spec/controllers/events_spec.cr
  src/controllers/application.cr
  src/controllers/events.cr
  src/controllers/utilities/multi_tenant.cr
Labels: type: enhancement

#284 feat: PPT-621 Add pagination to bookings index route
  OPENAPI_DOC.yml
  shard.lock
  spec/controllers/bookings_spec.cr
  src/controllers/bookings.cr
Labels: type: enhancement

#285 fix(events): use relative monthly bookings by default (PPT-651)
  shard.lock
  src/controllers/events.cr
Labels: type: bug
