Repository PlaceOS/staff-api, pull requests merged in 2024-02, with the labels that each got.

#312 chore(shard.lock): update shards
  OPENAPI_DOC.yml
  shard.lock
Labels: type: chore

#313 fix(events): [PPT-1190] update metadata on rapid destroy after create
  OPENAPI_DOC.yml
  shard.lock
  src/controllers/events.cr
Labels: type: bug

#314 fix(bookings): ensure serialisable transactions
  shard.lock
  src/controllers/bookings.cr
Labels: type: bug

#315 feat(events): add a reason for cancellation
  shard.lock
  src/controllers/events.cr
Labels: type: enhancement
